// Kanon 66 ksiąg — polskie nazwy + liczba rozdziałów. `id` to slug bez kropek
// (używany jako klucz w mapie postępu: `${id}_${rozdział}`).
export const BIBLE_BOOKS = [
  // ── Stary Testament (39) ──
  { id: 'rdz',  name: 'Rodzaju',              chapters: 50, testament: 'ST' },
  { id: 'wj',   name: 'Wyjścia',              chapters: 40, testament: 'ST' },
  { id: 'kpl',  name: 'Kapłańska',            chapters: 27, testament: 'ST' },
  { id: 'lb',   name: 'Liczb',                chapters: 36, testament: 'ST' },
  { id: 'pwt',  name: 'Powtórzonego Prawa',   chapters: 34, testament: 'ST' },
  { id: 'joz',  name: 'Jozuego',              chapters: 24, testament: 'ST' },
  { id: 'sdz',  name: 'Sędziów',              chapters: 21, testament: 'ST' },
  { id: 'rt',   name: 'Rut',                  chapters: 4,  testament: 'ST' },
  { id: '1sm',  name: '1 Samuela',            chapters: 31, testament: 'ST' },
  { id: '2sm',  name: '2 Samuela',            chapters: 24, testament: 'ST' },
  { id: '1krl', name: '1 Królewska',          chapters: 22, testament: 'ST' },
  { id: '2krl', name: '2 Królewska',          chapters: 25, testament: 'ST' },
  { id: '1krn', name: '1 Kronik',             chapters: 29, testament: 'ST' },
  { id: '2krn', name: '2 Kronik',             chapters: 36, testament: 'ST' },
  { id: 'ezd',  name: 'Ezdrasza',             chapters: 10, testament: 'ST' },
  { id: 'ne',   name: 'Nehemiasza',           chapters: 13, testament: 'ST' },
  { id: 'est',  name: 'Estery',               chapters: 10, testament: 'ST' },
  { id: 'hi',   name: 'Hioba',                chapters: 42, testament: 'ST' },
  { id: 'ps',   name: 'Psalmy',               chapters: 150, testament: 'ST' },
  { id: 'prz',  name: 'Przysłów',             chapters: 31, testament: 'ST' },
  { id: 'koh',  name: 'Koheleta',             chapters: 12, testament: 'ST' },
  { id: 'pnp',  name: 'Pieśń nad Pieśniami',  chapters: 8,  testament: 'ST' },
  { id: 'iz',   name: 'Izajasza',             chapters: 66, testament: 'ST' },
  { id: 'jr',   name: 'Jeremiasza',           chapters: 52, testament: 'ST' },
  { id: 'lm',   name: 'Lamentacje',           chapters: 5,  testament: 'ST' },
  { id: 'ez',   name: 'Ezechiela',            chapters: 48, testament: 'ST' },
  { id: 'dn',   name: 'Daniela',              chapters: 12, testament: 'ST' },
  { id: 'oz',   name: 'Ozeasza',              chapters: 14, testament: 'ST' },
  { id: 'jl',   name: 'Joela',                chapters: 3,  testament: 'ST' },
  { id: 'am',   name: 'Amosa',                chapters: 9,  testament: 'ST' },
  { id: 'ab',   name: 'Abdiasza',             chapters: 1,  testament: 'ST' },
  { id: 'jon',  name: 'Jonasza',              chapters: 4,  testament: 'ST' },
  { id: 'mi',   name: 'Micheasza',            chapters: 7,  testament: 'ST' },
  { id: 'na',   name: 'Nahuma',               chapters: 3,  testament: 'ST' },
  { id: 'ha',   name: 'Habakuka',             chapters: 3,  testament: 'ST' },
  { id: 'so',   name: 'Sofoniasza',           chapters: 3,  testament: 'ST' },
  { id: 'ag',   name: 'Aggeusza',             chapters: 2,  testament: 'ST' },
  { id: 'za',   name: 'Zachariasza',          chapters: 14, testament: 'ST' },
  { id: 'ml',   name: 'Malachiasza',          chapters: 4,  testament: 'ST' },
  // ── Nowy Testament (27) ──
  { id: 'mt',   name: 'Mateusza',             chapters: 28, testament: 'NT' },
  { id: 'mk',   name: 'Marka',                chapters: 16, testament: 'NT' },
  { id: 'lk',   name: 'Łukasza',              chapters: 24, testament: 'NT' },
  { id: 'j',    name: 'Jana',                 chapters: 21, testament: 'NT' },
  { id: 'dz',   name: 'Dzieje Apostolskie',   chapters: 28, testament: 'NT' },
  { id: 'rz',   name: 'Rzymian',              chapters: 16, testament: 'NT' },
  { id: '1kor', name: '1 Koryntian',          chapters: 16, testament: 'NT' },
  { id: '2kor', name: '2 Koryntian',          chapters: 13, testament: 'NT' },
  { id: 'ga',   name: 'Galatów',              chapters: 6,  testament: 'NT' },
  { id: 'ef',   name: 'Efezjan',              chapters: 6,  testament: 'NT' },
  { id: 'flp',  name: 'Filipian',             chapters: 4,  testament: 'NT' },
  { id: 'kol',  name: 'Kolosan',              chapters: 4,  testament: 'NT' },
  { id: '1tes', name: '1 Tesaloniczan',       chapters: 5,  testament: 'NT' },
  { id: '2tes', name: '2 Tesaloniczan',       chapters: 3,  testament: 'NT' },
  { id: '1tm',  name: '1 Tymoteusza',         chapters: 6,  testament: 'NT' },
  { id: '2tm',  name: '2 Tymoteusza',         chapters: 4,  testament: 'NT' },
  { id: 'tt',   name: 'Tytusa',               chapters: 3,  testament: 'NT' },
  { id: 'flm',  name: 'Filemona',             chapters: 1,  testament: 'NT' },
  { id: 'hbr',  name: 'Hebrajczyków',         chapters: 13, testament: 'NT' },
  { id: 'jk',   name: 'Jakuba',               chapters: 5,  testament: 'NT' },
  { id: '1p',   name: '1 Piotra',             chapters: 5,  testament: 'NT' },
  { id: '2p',   name: '2 Piotra',             chapters: 3,  testament: 'NT' },
  { id: '1j',   name: '1 Jana',               chapters: 5,  testament: 'NT' },
  { id: '2j',   name: '2 Jana',               chapters: 1,  testament: 'NT' },
  { id: '3j',   name: '3 Jana',               chapters: 1,  testament: 'NT' },
  { id: 'jud',  name: 'Judy',                 chapters: 1,  testament: 'NT' },
  { id: 'ap',   name: 'Apokalipsa',           chapters: 22, testament: 'NT' },
]

export const TOTAL_CHAPTERS = BIBLE_BOOKS.reduce((s, b) => s + b.chapters, 0) // 1189
export const chapterKey = (bookId, chapter) => `${bookId}_${chapter}`
