export const DEFAULT_EXPENSE_CATEGORIES = [
  { id: 'jedzenie',      label: 'Jedzenie',       icon: '🍕', color: '#C97A55' },
  { id: 'kawa',          label: 'Kawa / Cafe',     icon: '☕', color: '#A07B4F' },
  { id: 'restauracje',   label: 'Restauracje',     icon: '🍽️', color: '#C97A55' },
  { id: 'zakupy',        label: 'Zakupy',          icon: '🛒', color: '#D4A574' },
  { id: 'ubrania',       label: 'Ubrania',         icon: '👕', color: '#9B8FA8' },
  { id: 'transport',     label: 'Transport',       icon: '🚌', color: '#9AAFB8' },
  { id: 'auto',          label: 'Auto',            icon: '🚗', color: '#7A9E9A' },
  { id: 'paliwo',        label: 'Paliwo',          icon: '⛽', color: '#E0B570' },
  { id: 'dom',           label: 'Dom',             icon: '🏠', color: '#8A7E72' },
  { id: 'rachunki',      label: 'Rachunki',        icon: '📄', color: '#BAAE99' },
  { id: 'naprawy',       label: 'Naprawy',         icon: '🔧', color: '#A07B4F' },
  { id: 'zdrowie',       label: 'Zdrowie',         icon: '💊', color: '#A8B5A0' },
  { id: 'kosmetyki',     label: 'Kosmetyki',       icon: '💄', color: '#B89090' },
  { id: 'sport',         label: 'Sport',           icon: '🏃', color: '#A8B5A0' },
  { id: 'rozrywka',      label: 'Rozrywka',        icon: '🎬', color: '#C97A55' },
  { id: 'ksiazki',       label: 'Książki',         icon: '📚', color: '#9AAFB8' },
  { id: 'edukacja',      label: 'Edukacja',        icon: '🎓', color: '#9AAFB8' },
  { id: 'elektronika',   label: 'Elektronika',     icon: '💻', color: '#7A9E9A' },
  { id: 'subskrypcje',   label: 'Subskrypcje',     icon: '🔄', color: '#8A7E72' },
  { id: 'wyjazdy',       label: 'Wyjazdy',         icon: '✈️', color: '#E0B570' },
  { id: 'prezenty',      label: 'Prezenty',        icon: '🎁', color: '#D4A574' },
  { id: 'zwierzeta',     label: 'Zwierzęta',       icon: '🐾', color: '#A8B5A0' },
  { id: 'praca',         label: 'Praca',           icon: '💼', color: '#BAAE99' },
  { id: 'firma',         label: 'Firma',           icon: '🏢', color: '#9AAFB8' },
  { id: 'dziesiecina',   label: 'Dziesięcina',     icon: '⛪', color: '#C97A55' },
  { id: 'ofiara',        label: 'Ofiara / Datek',  icon: '🕊️', color: '#D4A574' },
  { id: 'oszczednosci',  label: 'Oszczędności',    icon: '🏦', color: '#A8B5A0' },
  { id: 'inne',          label: 'Inne',            icon: '📌', color: '#7A6E5C' },
]

export const DEFAULT_INCOME_CATEGORIES = [
  { id: 'wynagrodzenie', label: 'Wynagrodzenie',   icon: '💼', color: '#A8B5A0' },
  { id: 'freelance',     label: 'Freelance',       icon: '💻', color: '#A8B5A0' },
  { id: 'premia',        label: 'Premia',          icon: '⭐', color: '#E0B570' },
  { id: 'zwrot',         label: 'Zwrot',           icon: '↩️', color: '#9AAFB8' },
  { id: 'prezent',       label: 'Prezent',         icon: '🎁', color: '#D4A574' },
  { id: 'inwestycje',    label: 'Inwestycje',      icon: '📈', color: '#A8B5A0' },
  { id: 'wynajem',       label: 'Wynajem',         icon: '🏠', color: '#C97A55' },
  { id: 'sprzedaz',      label: 'Sprzedaż',        icon: '🛒', color: '#D4A574' },
  { id: 'stypendium',    label: 'Stypendium',      icon: '🎓', color: '#9AAFB8' },
  { id: 'inne',          label: 'Inne',            icon: '📌', color: '#7A6E5C' },
]

export const CAT_COLORS = [
  '#C97A55','#A07B4F','#D4A574','#A8B5A0','#9AAFB8',
  '#E0B570','#9B8FA8','#B89090','#7A9E9A','#8A7E72',
  '#BAAE99','#7A6E5C','#C97A55','#D4A574','#A8B5A0',
]
